language: node_js

node_js:
  - "12.9.0"

install:
  - npm install

script:
  - npm run test

jobs:
  include:
    - stage: Produce Coverage
      node_js: "12.9.0"
      script: npm run test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
